### PR TITLE
Partial Mac OS Support

### PR DESCRIPTION
**Pull request by Ziugy**
Addresses issues with running on Mac OS - #41
- Get-UnitySetupInstance
- Get-UnityProjectInstance
- Start-UnityEditor

Still to do:
- Installing Unity version onto the Mac machine. (Find-UnitySetupInstaller)

### CODE REVIEW

**Comment by jwittner** [comment]
@Ziugy  Bah, looks like my changes added conflicts. You'll have to merge develop into your branch or rebase.

**Comment by Ziugy** [comment]
@jwittner Resolved!

**Comment by Ziugy** [comment]
Dropped `Setup` in favor of the OS running the script. Cleaned up platform through `Get-OperatingSystem` and the `[OperatingSystem]` enumeration. Added in exception handling in functions where functionality isn't implemented yet.

**Comment by jwittner** [comment]
Tested on Windows and Linux and got expected results. Great work! Can't wait for full support. ;)

**Pull request merged**
